version: '{build}'
skip_tags: true
image: Visual Studio 2017
build_script:
- ps: ./Build.ps1 -majorMinor "2.1" -patch "$env:APPVEYOR_BUILD_VERSION" -customLogger "C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: SerilogWeb.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: frO9AV5IKcjFl89cRljaCBPGnDVOkMRJg5vB5uE4U+D70vgVUlJ/WqLY+n20fHAQ
  skip_symbols: true
  on:
    branch: master
