version: '{build}'
image: Visual Studio 2017
build_script:
- ps: ./Build.ps1 -majorMinor "0.1" -patch "$env:APPVEYOR_BUILD_VERSION" -customLogger "C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: SerilogWeb.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: RKWJyeIQtpcfdYoghDQ46d1BnP9ouE5bifxbxVLpV1jW/hfu9BartYv9RYi5kZch
  skip_symbols: true
  on:
    branch: master
